# === APP ===
spring.application.name=weather-app

# === DATA BASE ===
spring.datasource.url=jdbc:postgresql://localhost:5432/weather_app
spring.datasource.username=postgres
spring.datasource.password=1234

# === HIBERNATE ===
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.enabled=false

# === SESSION SETTINGS ===
session.expiration-hours=24

# === WEATHER API ===
weather.api.key=1c70fd0697836268d872c59c87447816
weather.geo.url=https://api.openweathermap.org/geo/1.0/direct
weather.weather.url=https://api.openweathermap.org/data/2.5/weather
